---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_lxc_hosts_container_build_command: >-
  debootstrap --variant minbase
  --include ca-certificates
  {{ ansible_facts['distribution_release'] }}
  /var/lib/machines/{{ lxc_container_base_name }}
  {{ lxc_apt_mirror }}

_lxc_copy_from_host:
  - /etc/apt/sources.list
  - /etc/apt/sources.list.d/
  - /etc/apt/apt.conf.d/
  - /etc/apt/trusted.gpg.d/
  - /etc/apt/trusted.gpg
  - /etc/apt/preferences.d/
  - /etc/apt/mirrors/
  - /etc/environment
  - /etc/localtime
  - /etc/protocols

_lxc_cache_prep_template: "prep-scripts/debian_prep.sh.j2"

_lxc_cache_distro_libpython:
  bullseye: libpython3.9
  jammy: libpython3.10
  bookworm: libpython3.11
  noble: libpython3.12

_lxc_cache_need_systemd_resolved: >-
  {{
    ansible_facts['distribution'] == 'Debian' or
    (ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version'] is ansible.builtin.version('24', 'ge'))
  }}

# This list should contain a minimum set of packages. Add extra packages via roles that require them.
_lxc_cache_distro_packages:
  - ca-certificates
  - dbus
  - git # needed everywhere when wheel_build=false
  - iputils-ping
  - iproute2
  - libxml2
  - locales
  - netbase
  - procps # needed for sysctl-container.service
  - python3
  - "{{ _lxc_cache_distro_libpython[ansible_facts['distribution_release'] | lower] }}"
  - sudo
  - systemd
  - systemd-sysv
  - "{{ _lxc_cache_need_systemd_resolved | ternary('systemd-resolved', '') }}"
  - udev
  - tzdata
